import { Product } from './types';

export const products: Product[] = [
  // Men's Items (4)
  {
    id: 'm1',
    name: 'Bengaluru Streets Oversized Tee',
    slug: 'bengaluru-streets-oversized-tee',
    description: 'A comfortable oversized tee perfect for the Bengaluru weather. 100% Cotton.',
    price: 599,
    original_price: 899,
    category: 'T-shirts',
    gender: 'Men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ink', 'Mint'],
    images: ['https://picsum.photos/seed/m1/600/800', 'https://picsum.photos/seed/m1b/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm2',
    name: 'Classic Urban Polo',
    slug: 'classic-urban-polo',
    description: 'Keep it classy with this premium cotton polo tee.',
    price: 699,
    original_price: null,
    category: 'T-shirts',
    gender: 'Men',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'White'],
    images: ['https://picsum.photos/seed/m2/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm3',
    name: 'Tech Bro Hoodie',
    slug: 'tech-bro-hoodie',
    description: 'Essential gear for the startup ecosystem. Co-founder approved.',
    price: 1299,
    original_price: 1599,
    category: 'Hoodies',
    gender: 'Men',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Lavender'],
    images: ['https://picsum.photos/seed/m3/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'm4',
    name: 'Indiranagar Casual Shirt',
    slug: 'indiranagar-casual-shirt',
    description: 'A breezy shirt for those Sunday brunches in Indiranagar.',
    price: 899,
    original_price: 1199,
    category: 'Shirts',
    gender: 'Men',
    sizes: ['M', 'L', 'XL'],
    colors: ['Mint', 'White'],
    images: ['https://picsum.photos/seed/m4/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  
  // Women's Items (4)
  {
    id: 'w1',
    name: 'Malleshwaram Block Print Kurta',
    slug: 'malleshwaram-block-print-kurta',
    description: 'Traditional elegance meets modern comfort. Authentic block print.',
    price: 1199,
    original_price: 1499,
    category: 'Ethnic',
    gender: 'Women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blush', 'Ink'],
    images: ['https://picsum.photos/seed/w1/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'w2',
    name: 'Festive Anarkali Set',
    slug: 'festive-anarkali-set',
    description: 'Complete set for the festive season with intricate detailing.',
    price: 1499,
    original_price: 1999,
    category: 'Ethnic',
    gender: 'Women',
    sizes: ['S', 'M', 'L'],
    colors: ['Mint', 'Lavender'],
    images: ['https://picsum.photos/seed/w2/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'w3',
    name: 'Koramangala Crop Tee',
    slug: 'koramangala-crop-tee',
    description: 'Trendy crop top for the perfect evening out.',
    price: 399,
    original_price: null,
    category: 'T-shirts',
    gender: 'Women',
    sizes: ['S', 'M', 'L'],
    colors: ['Blush', 'White'],
    images: ['https://picsum.photos/seed/w3/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'w4',
    name: 'Silk Blend Ethnic Tunic',
    slug: 'silk-blend-ethnic-tunic',
    description: 'Rich silk blend fabric tunic for a regal look.',
    price: 999,
    original_price: 1299,
    category: 'Ethnic',
    gender: 'Women',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Mint', 'Ink'],
    images: ['https://picsum.photos/seed/w4/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },

  // Custom Print Items (2)
  {
    id: 'c1',
    name: 'Your Logo Custom Tee',
    slug: 'your-logo-custom-tee',
    description: 'Upload your design and we will print it on our premium cotton tees.',
    price: 499,
    original_price: null,
    category: 'Custom Print',
    gender: 'Unisex',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Lavender', 'Mint'],
    images: ['https://picsum.photos/seed/c1/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'c2',
    name: 'College Fest Batch Shirts',
    slug: 'college-fest-batch-shirts',
    description: 'Bulk custom tees perfect for college fests in Bengaluru. Minimum order 20.',
    price: 399,
    original_price: 599,
    category: 'Custom Print',
    gender: 'Unisex',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy', 'Red', 'Black'],
    images: ['https://picsum.photos/seed/c2/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },

  // Unisex Items (2)
  {
    id: 'u1',
    name: 'Namma Bengaluru Essential Hoodie',
    slug: 'namma-bengaluru-essential-hoodie',
    description: 'Show your love for the city with this essential winter hoodie.',
    price: 1199,
    original_price: 1499,
    category: 'Hoodies',
    gender: 'Unisex',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ink', 'Lavender'],
    images: ['https://picsum.photos/seed/u1/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'u2',
    name: 'Filter Coffee Graphic Tee',
    slug: 'filter-coffee-graphic-tee',
    description: 'Because filter coffee is not just a drink, it is an emotion.',
    price: 499,
    original_price: 699,
    category: 'T-shirts',
    gender: 'Unisex',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blush', 'Mint', 'White'],
    images: ['https://picsum.photos/seed/u2/600/800'],
    in_stock: true,
    created_at: new Date().toISOString(),
  }
];
